--GM:Include("cl_freelook.lua")
GM:Include("sh_corpsefade.lua")
GM:Include("sh_money.lua")
GM:Include("sh_player_remover.lua")

GM:LoadFolder(ContentFolder .. "_defines/")
GM:LoadFolder(ContentFolder .. "settings/")
GM:LoadFolder(ContentFolder .. "commands/")
GM:LoadFolder(ContentFolder .. "logs/")
GM:LoadFolder(ContentFolder .. "actions/")

Badge.Load()
Language.Load()

Animation.RegisterFolder(ContentFolder .. "animations/")
CharacterCreate.RegisterFolder(ContentFolder .. "chartypes/")
CharacterFlag.RegisterFolder(ContentFolder .. "flags/")
CharacterGen.RegisterFolder(ContentFolder .. "chargens/")
Chat.RegisterFolder(ContentFolder .. "chat/")
Item.RegisterFolder(ContentFolder .. "items/")
Hud.RegisterFolder(ContentFolder .. "hud/")
buff.RegisterFolder(ContentFolder .. "buffs/")
