IRON_HOLSTERED 		= 0
IRON_HOLSTERED2IDLE = 1
IRON_IDLE 			= 2
IRON_IDLE2AIM 		= 3
IRON_AIM 			= 4

RELOADTYPE_NONE		= 0
RELOADTYPE_NORMAL	= 1
RELOADTYPE_SHOTGUN	= 2

SONG_IDLE 		= 0
SONG_ALERT 		= 1
SONG_ACTION 	= 2
SONG_STINGER 	= 3

--teams need reorganising for tekka
TEAM_CITIZEN		= 1
TEAM_SKYNET			= 2
TEAM_REPROG 		= 3
TEAM_GREY 			= 4
TEAM_AOF 			= 5
