INV_WORLD = 0
INV_PLAYER = 1
INV_STASH = 2
INV_ITEM = 3
INV_CONTAINER = 4

RARITY_COMMON = 1
RARITY_UNCOMMON = 2
RARITY_RARE = 3
RARITY_EPIC = 4
RARITY_LEGENDARY = 5
RARITY_ARTIFACT = 6
RARITY_DEVELOPER = 7

TAB_LOOC	= 2^1
TAB_OOC		= 2^2
TAB_IC		= 2^3
TAB_ADMIN	= 2^4
TAB_PM		= 2^5
TAB_RADIO	= 2^6

TOOLTRUST_BANNED = 0
TOOLTRUST_BASIC = 1
TOOLTRUST_ADVANCED = 2

PHYSTRUST_BANNED = 0
PHYSTRUST_ENABLED = 1

PROPTRUST_BANNED = 0
PROPTRUST_ENABLED = 1
