INV_NULL = -1
INV_WORLD = 0
INV_PLAYER = 1
INV_STASH = 2
INV_ITEM = 3
INV_CONTAINER = 4

RARITY_COMMON = 1
RARITY_UNCOMMON = 2
RARITY_RARE = 3
RARITY_EPIC = 4
RARITY_LEGENDARY = 5
RARITY_ARTIFACT = 6
RARITY_DEV = 7
